# Generated by Django 5.2.3 on 2025-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='shares-name')),
                ('description', models.CharField(max_length=256, verbose_name='shares-description')),
                ('date_before', models.DateTimeField(blank=True, verbose_name='date-before')),
                ('status', models.CharField(choices=[('DISCOUNT', 'СКИДКИ'), ('TOP', 'ТОП'), ('BENEFIT', 'ВЫГОДА')], default='BENEFIT', verbose_name='articl-shares')),
            ],
            options={
                'db_table': 'Акции компании',
            },
        ),
    ]
