# Generated by Django 5.2.3 on 2025-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='status',
            field=models.CharField(choices=[('СКИДКИ', 'СКИДКИ'), ('РАСПРОДАЖА', 'РАСПРОДАЖА'), ('ВЫГОДА', 'ВЫГОДА'), ('НОВИНКИ', 'НОВИНКИ'), ('СЕЗОННЫЕ', 'СЕЗОННЫЕ')], default='BENEFIT', verbose_name='articl-shares'),
        ),
    ]
