# Generated by Django 5.2.3 on 2025-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0002_alter_shares_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='views',
            field=models.IntegerField(default=0, verbose_name='count-of-view'),
        ),
    ]
