# Generated by Django 5.2.3 on 2025-06-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
