# Generated by Django 5.2.3 on 2025-07-01 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='discount-percentage'),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
    ]
